### ISSUE TITLE
Text block

### ISSUE THREAD

**Issue by simplybenuk** [nhsengland/futurenhs-roadmap#5]
### Summary
Text block allows user to present rich text content on a platform page or group homepage

### Intended outcome
Improve the speed at which group admins can build pages of content on the platform

### How it will work
The Text block is a building block of a page. It allows a group admin to present a row of rich text that will be presented back to viewers of a page.

The first block that will be made will be the rich text block

![image](https://user-images.githubusercontent.com/9471595/135879373-a359b1bf-6a8a-432a-9f38-91f71470c6c1.png)

**Comment by the-adonis** [comment]
Create PAGES
